from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

# remove no need file.
if GetDepend('RT_USING_RTGUI') == False:
	SrcRemove(src, 'calculator.c')
	SrcRemove(src, 'ui_button.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
